Menambah Algoritma Insertion Sort
Pemrograman-Fasilkom-Unej/python-algorithms pull request #5
Opened 2020-10-12 10:05 UTC by phanatagama

### **Jelaskan perubahan:**
Menambah algorima insertion sort dan update file readme.md

* [x] Menambah Algoritma
* [ ] Memperbaiki kesalahan penulisan pada algoritma yang sudah ada? 
* [x] Memperbaiki dokumentasi

### **Checklist:**
* [x] Saya sudah membaca [CONTRIBUTING.md](https://github.com/Pemrograman-Fasilkom-Unej/python-algorithms/blob/master/CONTRIBUTING.md).
* [ ] Setiap algoritma yang ditambahkan, sudah mempunyai sumber dan refrensi yang cukup.
* [x] Saya sudah menulis kode dengan jelas

2020-10-12 13:32 UTC, miqdadyyy commented on sorting/insertion_sort.py
> +     currentvalue = array[index]
gunakan snake case pada variable ini

2020-10-12 13:34 UTC, miqdadyyy requested changes
rapikan kode seperti space dan lain2
dan juga nama variabel menggunakan snake_case
untuk hasil dari sorting tampung dalam sebuah variabel dulu jangan langsung dipanggil di fungsi print

2020-10-14 05:52 UTC, evaleries commented
Looks good to me.
Re-check please @miqdadyyy

2020-10-14 06:50 UTC, miqdadyyy commented
LGTM

2020-10-14 06:50 UTC, miqdadyyy approved these changes

2020-10-14 06:50 UTC, merged